name: Super Linter

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super Linter
        uses: github/super-linter/slim@v6
        env:
          VALIDATE_ALL_CODEBASE: true        # Lint the entire repo, not just changed files
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSHARP: true
          VALIDATE_YAML: true
          VALIDATE_JSON: false
          VALIDATE_MARKDOWN: false
          SUPPRESS_WARNINGS: false